### ISSUE TITLE
Individual Wallet Monitoring Bot

### ISSUE THREAD

**Issue by funderbrker** [BeanstalkFarms/Beanstalk-Py#7]
A bot that monitors individual wallets and reports hourly/daily changes to a user's DMs. Similar to the current Seasons bot but on an individual level.

**Comment by funderberker** [comment]
Currently the scope of information necessary to do this is not available. Due to scaling needs all data must be present in the subgraph for efficient access. This will require notable subgraph development to implement data on a peer-wallet basis.

The minimum data to make a useful bot would be seasonal wallet status containing:
1. Silo balances (BDV or amount)
2. pods/plots owned (including earliest position)
3. earned beans

More data could be added in on the fly after this.

**Comment by funderberker** [comment]
#2 PR includes most of the python code necessary for implementation, although it has likely gown stale with the replant.
